В этом блокноте мы постоим график японских свечей.

Для начала подключаем библиотеку pandas и загружаем интересующий нас файл при помощи метода `read_csv(file_name, delimeter, index_col, decimal, usecols, header, ...)`.

In [ ]:
import pandas as pd
data = pd.read_csv('SPFB.RTS-12.18_180901_181231.csv',
                       delimiter=',',
                       decimal='.')

 Посмотрим на наши данные. Похоже, они загрузились правильно.

In [ ]:
data.head()

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1

Можно окинуть взглядом и весь набор данных:

In [ ]:
data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1
...,...,...,...,...,...,...,...,...,...
58965,SPFB.RTS-12.18,1,20/12/18,18:40,109380.0,109380.0,109380.0,109380.0,1
58966,SPFB.RTS-12.18,1,20/12/18,18:41,109380.0,109390.0,109380.0,109390.0,10
58967,SPFB.RTS-12.18,1,20/12/18,18:43,109380.0,109390.0,109380.0,109390.0,12
58968,SPFB.RTS-12.18,1,20/12/18,18:44,109390.0,109390.0,109390.0,109390.0,3
58969,SPFB.RTS-12.18,1,20/12/18,18:45,109390.0,109390.0,109380.0,109380.0,3

Преобразуем дату в удобный для дальнейшего формат, склеив дату и время

In [ ]:
data['DATE'] = data['<DATE>'] + ' ' + data['<TIME>']
data.head()

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,DATE
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3,03/09/18 10:01
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5,03/09/18 10:02
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8,03/09/18 10:04
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1,03/09/18 10:05
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1,03/09/18 10:08

Поработаем над форматом времени. Для этого переведем строковые данные, показывающие время, в специальный объект в Python.

In [ ]:
data['DATE'] = pd.to_datetime(data['DATE'], format="%d/%m/%y %H:%M")
data.head()

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,DATE
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3,2018-09-03 10:01:00
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5,2018-09-03 10:02:00
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8,2018-09-03 10:04:00
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1,2018-09-03 10:05:00
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1,2018-09-03 10:08:00

Сформируем интересующую нас выборку

In [ ]:
df_filtered = data[data['DATE'].dt.strftime('%Y-%m-%d') == '2018-09-07']

Теперь полная дата будет для нас индеком объектов

In [ ]:
df_filtered = df_filtered.set_index('DATE')

Выберем только интересующие для построения столбцы:

In [ ]:
df_filtered = df_filtered[['<OPEN>','<HIGH>','<LOW>','<CLOSE>']]

Переименуем (для удобства) столбцы:

In [ ]:
df_filtered.columns =['open', 'high', 'low', 'close']
df_filtered.head()

                         open      high       low     close
DATE
2018-09-07 10:01:00  104750.0  104900.0  104750.0  104880.0
2018-09-07 10:02:00  104840.0  104940.0  104840.0  104940.0
2018-09-07 10:03:00  104950.0  105040.0  104950.0  104950.0
2018-09-07 10:04:00  104950.0  105000.0  104940.0  105000.0
2018-09-07 10:05:00  105000.0  105000.0  105000.0  105000.0

Проведем агрегацию данных для построения графика свечей:

In [ ]:
d2 = df_filtered.resample('1H').agg({'open':'first',
                                     'high':'max',
                                     'low':'min',
                                     'close':'last'})

Осталось подключить необходимую библиотеку и построить:

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Candlestick(x=d2.index,
                open=d2['open'],
                high=d2['high'],
                low=d2['low'],
                close=d2['close'])])

fig.show()